using Transflower.InventoryManagement.InitialRequests.Repositories.Interfaces;
namespace Transflower.InventoryManagement.InitialRequests.Services.Interfaces;
public interface IInitialRequestService : IInitialRequestRepository
{
}